
export const CREAT_PAYMENT_REQUEST = 'CREAT_PAYMENT_REQUEST'
export const CREAT_PAYMENT_SUCCESS = 'CREAT_PAYMENT_SUCCESS'
export const CREAT_PAYMENT_FAILURE = 'CREAT_PAYMENT_FAILURE'

export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST'
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS'
export const UPDATE_PAYMENT_FAILURE = 'UPDATE_PAYMENT_FAILURE'


