
export const CREAT_ORDER_REQUEST = 'CREAT_ORDER_REQUEST'
export const CREAT_ORDER_SUCCESS = 'CREAT_ORDER_SUCCESS'
export const CREAT_ORDER_FAILURE = 'CREAT_ORDER_FAILURE'

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST'
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS'
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE'

